name: cardyx-frontend

services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ""
        CARDYX_INTERNAL_API_URL: http://127.0.0.1:4000
    container_name: cardyx-frontend
    restart: unless-stopped
    network_mode: host