services:
  api:
    environment:
      RUN_POOL_STATE_INDEXER: "true"
      RUN_BALANCE_REFRESH: "false"
      CARDYX_POOL_STATE_BATCH_SIZE: "100"
      CARDYX_POOL_STATE_BATCHES_PER_POOL: "1"
      CARDYX_POOL_STATE_POOLS_PER_RUN: "25"
